### ISSUE TITLE
Proba

### ISSUE THREAD

**Issue by fir3scq** [fir3scq/proba#1]
# Automated Runner Image Creation

The automated-images project uses pipeline to generate automatic disk images for Ubuntu 20.04/22.04 using Packer.

Each image is configured by a JSON or HCL2 Packer template that specifies where to build the image and what steps to run to install software and prepare the disk.

The Packer process initializes a connection to the Azure subscription and creates temporary resources required for the build the image using ARM, followed by cleanup of all the temporary resources created.

All the packer definitions and scripts are taken from the official [github repo](https://github.com/actions/runner-images/tree/main)  with all the code to build images of all kind os OS and also provides further information about the process.

# Index

- [Portal AzureDevOps](#portalazuredevops)
- [Requirements](#requirements)
- [Pipeline](#pipeline)
  - [Parameters](#parameters)
  - [Variables](#variables)
  - [Tasks](#tasks)
    - [AzureKeyVault@2](#azurekeyvault@2)
    - [CmdLine@2](#cmdline@2)
    - [AzureCLI@2](#azurecli@2)

# Portal AzureDevOps

This portal will be the place where we will generate the code and where we will execute it to check the correct functioning of the automation. Inside the portal we will only import the following two sections: Repos and Pipelines, which will be the ones we will use.

![portal azure devops.png](./4.png)

In the Repos section will be where the .yml file will be generated where the code used for the execution of the automatism of the image will be.

![repo view.png](./photos/1.png)

To generate a new file inside Repos, go to the Files section and click on the three buttons on the right, then click on new and then on file.

![repo new file.png](./photos/10.png)

In the Pipeline section will be where we execute the .yml file that will also be used to check that the automatism works correctly.

![pipeline view.png](./photos/5.png)

To start the pipeline, go to the pipelines section and click on the run pipeline button. 

![pipeline run bottton.png](./photos/6.png)

Add the requested parameters and the pipeline is initialised.

![pipeline execution data.png](./photos/7.png)

From this section we can also check the status of the task and see if it was executed correctly or if there is any error in the code.

![pipeline status task.png](./photos/8.png)

![pipeline review command.png](./photos/9.png)

# Requirements
For this pipeline to be executed successfully, there are several items which must be created beforehand:

| Item | Description
| ------------ | -----------
| Resource Group | On wich the rest of the items are created, as well as where the images will be created.
| Image Gallery | Where the different image definitions are created.
| Image Definition | A list of versions of a certain image. There must be 2 of them, one for the Ubuntu 20.04 version and other for the 22.04
| Service Connections | The connection of Azure DevOps with a Service principal whith contributor role over the resource group on wich the image is going to be deployed.

# Pipeline

The aim is to automatically generate new versions of the images from a code.

## Parameters

  ```
parameters:
- name: ImageName
  displayName: Image Name
  type: string
  default: 
- name: ImageVersion
  displayName: Image version
  type: string
  default: Check the appropiate value reviewing the versions on the image definition according to the nomenclature
- name: UbuntuVersion
  displayName: Ubuntu Version
  type: string
  default: 20
  values:
  - 20
  - 22
  ```

| Template par | Description
| ------------ | -----------
| `ImageName` | Tha name of the image that will be created, make sure that this name does not match with iny other image in the subscription.
| `ImageVersion` | The version that the image will be set as on the image definition. Make sure to review which version is the appropiate according to the last image created.
| `UbuntuVersion` | The ubuntu version of the image that will be created, wich can be 20 or 22, both on their lts versions (*.04)

## Variables

  ```
variables:
- name: ImageResourceGroupName
  value: "..." 
- name: ImageGalleryName
  value: "..." 
- name: TemplatePath
  ${{ if eq( parameters['UbuntuVersion'], '20') }}:
    value: "./images/linux/ubuntu2004.json"
  ${{ if eq( parameters['UbuntuVersion'], '22' ) }}:
    value: "./images/linux/ubuntu2204.pkr.hcl"
- name: ImageDefinitionName
  ${{ if eq( parameters['UbuntuVersion'], '20') }}:
    value: "...20"
  ${{ if eq( parameters['UbuntuVersion'], '22' ) }}:
    value: "...22"
  ```

| Template var | Description
| ------------ | -----------
| `ImageResourceGroupName` | Resource group name under which the task will be performed.
| `ImageGalleryName` | Azure compute gallery name on which the new version of the image will be added.
| `TemplatePath` | Path of the definition file used to generete the images whith the ubuntu version chosen, each ubuntu version has a specific file to use.
| `ImageDefinitionName` |  Image definition name (from the ImageGalleryName set before), on which the new version of the image will be added. Each OS version must have an image definition to it, so the images created from such version are attached to the same Image Definition and can be used afterwards.

## Tasks

This section discusses the tasks to be carried out in the pipeline for the creation of the new image and its attachment to the Image Definition as a new version.

### AzureKeyVault@2

This task takes the different key-vault secrets and attaches the values with an environment variable with the name of the secret.

  ```
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: '...'
      KeyVaultName: '...'
      SecretsFilter: '*'
      RunAsPreJob: true
  ```
These are the diferent values set when the task is run:

- `SubscriptionId` - The Azure subscription Id where resources will be created.
- `clientid` - The client ID of the Azure Service Principal attached to the DevOps service connection used.
- `secret-id` - The secret ID of the Azure Service Principal attached to the DevOps service connection used.
- `TenantId` - The id of the tenant on wich we try to interfere..

### CmdLine@2

This task clones a git repository where you can find the definitions used by packer and the different scripts applied in the process. After, it access the folder where the repository is cloned, and executes the packer command with a different file depending on whinch Ubuntu version is going to be created.

  ```
  - task: CmdLine@2
    inputs:
      script: |
        git clone https://github.com/actions/runner-images.git 
        cd ./runner-images
        sed -i 's/${{ parameters.UbuntuVersion }}_04-lts/${{ parameters.UbuntuVersion }}_04-lts-gen2/g' $(TemplatePath)
        packer build -var "subscription_id=$(SubscriptionId)" -var "client_id=$(clientid)" -var "client_secret=$(secret-id)" -var "managed_image_name=${{ parameters.ImageName }}" -var "managed_image_resource_group_name=$(ImageResourceGroupName)" -var "tenant_id=$(TenantId)" -var "build_resource_group_name=$(ImageResourceGroupName)" -var "vm_size=Standard_DC2s_v2" $(TemplatePath)  
  ```

The sed command is used to replace a string on a parameter included in the builders block of the packer definition, which is image_sku. Currently is set to 20_04-lts, but if we need to deploy the images by default on a v2 generation to use UEFI while booting the machines, we need to change the value to 20_04-lts-gen2. The number of the ubuntu version depends on the number selected in the UbuntuVersion parameter.

Also, the packer command calls a definition whose relative route from the repository root is inicialized as a variable which depends on the UbuntuVersion parameter. The -var parameters included are elements that are set with a default value on the packer definition, but as they need to be customized we overwrite them to set the values set in our variables and parameters.

Where:

- `SubscriptionId` - The Azure subscription Id where resources will be created. (key vault variable)
- `client_id` - The client ID of the Azure Service Principal attached to the DevOps service connection used. (key vault variable)
- `client_secret` - The secret ID of the Azure Service Principal attached to the DevOps service connection used. (key vault variable)
- `managed_image_name` - The name of the image that will be created. (parameter)
- `managed_image_resource_group_name` - The Azure resource group name where the Azure virtual machine will be created. (independent variable)
  - When running the packer command, several resources are created temporary with ARM in order to build the image, so in this case the parameter is set to use the yet created resource group to deploy such resources. Otherwise a temporary resource group could be create, wich would mean that permissions over the subscription scope may be granted to the service principal in use. 
- `tenant_id` - The Azure resource group name where the Azure virtual machine will be created. (key vault variable)
- `build_resource_group_name` - The resorce group on which the temporary ersources are created. (independent variable, same as managed_image_name)
- `vm_size` - The type of the temporary VM wich will be used to build the image. This must be a VM size compatible with the v2 generation of VM, which supports UEFI.

### AzureCLI@2

This task create a new image version wich the Ubuntu version chosen.

Where:

- `azureSubscription` - The service principal used to take the actions on the script.
- `scriptType` - As the task is running on a Linux VM, this option may be of kind `pscore` or `bash`.

  ```
  - task: AzureCLI@2
    inputs:
      azureSubscription: '...'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az sig image-version create --resource-group $(ImageResourceGroupName) --gallery-name $(ImageGalleryName) --gallery-image-definition $(ImageDefinitionName) --gallery-image-version ${{ parameters.ImageVersion }} --managed-image /subscriptions/$(SubscriptionId)/resourceGroups/$(ImageResourceGroupName)/providers/Microsoft.Compute/images/${{ parameters.ImageName }} --exclude-from-latest true
  ```
The az command itself creates a version of an image definition from the image created in the [CmdLine@2](#cmdline@2) task.
Parameters included:

- `resource-group` - Resource group name under which the task will be performed. 
- `gallery-name` - Azure compute gallery name on which the new version of the image will be added.
- `gallery-image-definition` - Image definition name (from the ImageGalleryName set before), on which the new version of the image will be added.
- `gallery-image-version` - The version that the image will be set as on the image definition. Make sure to review which version is the appropiate according to the last image created.
- `managed-image` - The image that will be put into as a version of the Image definition. It is the same as the image created on the [CmdLine@2](#cmdline@2) task.
- `exclude-from-latest` - Parameter in order to add the new version avoiding to set such version as "Latest", so it can be properly tested before setting the parameter as true and update the VM scale sets to use the created image.

![1](https://github.com/fir3scq/proba/assets/26067188/63bdbb5a-f43b-4bb6-ae59-2cd878d288c8)
<img width="955" alt="2" src="https://github.com/fir3scq/proba/assets/26067188/19cda167-9148-424c-8366-e27b3af9f3bc">
<img width="960" alt="3" src="https://github.com/fir3scq/proba/assets/26067188/092f01c5-046e-4e1b-8600-62fd6e94294d">
![4](https://github.com/fir3scq/proba/assets/26067188/75e6ff2c-56a9-449c-8aef-d55e10936d1e)
![5](https://github.com/fir3scq/proba/assets/26067188/a54f6cb1-9182-48b6-bde0-ce3e8f3d2d88)
![6](https://github.com/fir3scq/proba/assets/26067188/14bf36b6-5d7e-4b42-9408-68682d624036)
![7](https://github.com/fir3scq/proba/assets/26067188/2d067e19-42ee-43ae-adbb-2c34cec7f038)
![8](https://github.com/fir3scq/proba/assets/26067188/c1d73d75-14f3-4fb8-bd22-301588219f73)
![9](https://github.com/fir3scq/proba/assets/26067188/544ddc8c-5bc8-4b6f-936b-2477052328ca)
![10](https://github.com/fir3scq/proba/assets/26067188/9f07bc38-f9ad-4253-b029-26556027aefa)
